uint8 START_BELT = 1
uint8 STOP_BELT = 2
uint8 TOGGLE_EMERGENCY_STOP = 3
uint8 GET_EMERGENCY_STOP_STATUS = 4
uint8 RELEASE_EMERGENCY_STOP = 5
uint8 GET_GRIPPER_SENSOR_STATUS = 6
uint8 GET_BELT_STATUS = 7

uint8 command_number
float32 value
---
bool result
float32 value
